spring.application.name=demo02
spring.datasource.url=jdbc:postgresql://localhost:5432/remedio 
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-plataform=org.hibernate.dialect.PostgresSQLDialect