spring.application.name=demo02
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/demo01
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-plataform=org.hibernate.dialect.PostgresSQLDialect