spring.application.name=demo01
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
<<<<<<< HEAD
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
=======
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
>>>>>>> 7b10b4bbbabf033ecd5c0a6e8f80f91e8a14ffbf
